### ISSUE TITLE
Not required but prevents form from submission

### ISSUE THREAD

**Issue by AliMehraei** [upjs/facile-validator#229]
Dear @AliN11 
1- How to define a data-rule on input tag that it is not required but if the user enter something in the input, the entered value must be a positive number.
But now if the input element leaved blank, this package prevents form from submission.
The current defined rule is : **data-rules="number|min:1"**
_note: I know that we can use "nullable", but if an input tag is not required why we have to use "nullable"?_
2- we need a data rule to accept **space** in addition to **alpha**, **number** and **dashes**, like **alpha-num-dash-space**

**Comment by AliN11** [comment]
Hello.
> 1- How to define a data-rule on input tag that it is not required but if the user enter something in the input, the entered value must be a positive number

As explained in the docs, you can use `nullable` rule:
```html
<input data-rules="nullable|number|min:1" />
```

> note: I know that we can use "nullable", but if an input tag is not required why we have to use "nullable"?

In fact the `nullable` solves this problem. The `required` rule may be used with `bail` rule or as a standalone rule to make a field only required.

> 2- we need a data rule to accept space in addition to alpha, number and dashes, like alpha-num-dash-space

You can use `regex` rule to implement customized rules.

**Comment by AliMehraei** [comment]
Hi dear @AliN11 
`You can use regex rule to implement customized rules.`
In these case, how we can specify a unique message (with specific description, and not in general) to an error entry item result?
Thanks

**Comment by AliN11** [comment]
@AliMehraei No. Currently there is no way to do that. But the `field:error` hook may help.
