### ISSUE TITLE
[FR] Possibility to Add Errors coming from the Back-end

### ISSUE THREAD

**Issue by michtio** [upjs/facile-validator#336]
Hey @AliN11 

First of all thank you very much for this amazing package, I was wondering if the possibility exists to be able to inject additional error messages to it?

I would love to apply the server validation that is returning into the facile-validator to give a more streamlined experience.
This would allow to add a custom error to an input element.

**Comment by AliN11** [comment]
Hey @michtio,

If I understood well, you can do that by using [X-Prefixed Rules](https://github.com/upjs/facile-validator#x-prefixed-rules) or [Using your own language](https://github.com/upjs/facile-validator#using-your-own-language) or the mixing them.

Let me know if you have any other questions. Good luck.

**Comment by michtio** [comment]
Thank you for the reply @AliN11 , I'll have a play with it and come back if there are any additions needed or if it doesn't work as expected.

**Comment by AliN11** [comment]
@michtio You're welcome. Feel free to open the issue if you have any further questions.
