### ISSUE TITLE
New rule: includes not

### ISSUE THREAD

**Issue by svossen** [upjs/facile-validator#370]
Thanks for creating this library, it works really nice!

Although it would be great to have a rule to prevent certain words from being filled out. For example to prevent people from entering a URL into a field. I probably could also use an inverse matching regex for this, but then it wouldn’t be clear to the end-user what is wrong since the validation failed message would be to generic.

Or as mentioned before, the suggestion to have custom rules with a custom validation message would be helpful too.

**Comment by AliN11** [comment]
Hey @svossen. That's a great suggestion indeed. I'll work on it in my spare time. Thanks!

**Comment by AliN11** [comment]
Hey @svossen. Can you please take a look at this draft:
https://github.com/upjs/facile-validator/pull/371

**Comment by AliN11** [comment]
Implemented in https://github.com/upjs/facile-validator/pull/371
Thanks for you suggestion.

**Comment by svossen** [comment]
Great, thanks a lot!
